// scripts/gen-tokens/css.ts — `css/tokens.css`: `:root` structural tokens + dark semantic
// colours (also on `[data-theme="dark"]`), light colours on `[data-theme="light"]`, the
// high-contrast overrides and the `.sl-type-<role>` utility classes.

import { tokens } from "../../src/design/tokens";
import {
	durationsMs,
	kebab,
	PREFIX,
	px,
	resolveColor,
	shadow,
	type Theme,
	typeSize,
	typeSteps,
	unitMultiple,
} from "./resolve";

type Decl = readonly [name: string, value: string];

/** Structural tokens (Appendix F §2.3), theme-independent. */
function structuralDecls(): Decl[] {
	const out: Decl[] = [];
	const add = (name: string, value: string | number): void => {
		out.push([`${PREFIX}${name}`, String(value)]);
	};
	add("unit", px(tokens.unit));
	add("hairline", tokens.size.hairline);
	for (const [k, n] of Object.entries(tokens.space)) add(`space-${k}`, unitMultiple(n));
	for (const [k, n] of Object.entries(tokens.size.control))
		add(`size-control-${k}`, unitMultiple(n));
	for (const [k, ref] of Object.entries(tokens.size.icon)) {
		const step = ref.slice("type.".length);
		add(`size-icon-${k}`, `var(${PREFIX}type-size-${step})`);
	}
	add("size-touch", unitMultiple(tokens.size.touch));
	add("size-rail", unitMultiple(tokens.size.rail));
	for (const [k, v] of Object.entries(tokens.size.column)) add(`size-column-${kebab(k)}`, v);
	add("size-log-pane", unitMultiple(tokens.size.logPane));
	for (const [k, v] of Object.entries(tokens.radius))
		add(`radius-${k}`, typeof v === "number" ? unitMultiple(v) : v);
	for (const [k, v] of Object.entries(tokens.type.family)) add(`type-family-${k}`, v);
	for (const step of typeSteps()) {
		const size = typeSize(step);
		const leading = tokens.type.leading[step];
		if (leading % tokens.unit !== 0 || leading < size)
			throw new Error(`type.leading.${step}=${leading} is not a lattice multiple ≥ ${size}`);
		add(`type-size-${step}`, px(size));
		add(`type-leading-${step}`, px(leading));
	}
	for (const [k, v] of Object.entries(tokens.type.weight)) add(`type-weight-${k}`, v);
	for (const [k, v] of Object.entries(tokens.type.tracking)) add(`type-tracking-${k}`, v);
	for (const [k, v] of Object.entries(tokens.type.features)) add(`type-features-${k}`, v);
	for (const [k, v] of Object.entries(durationsMs())) add(`motion-duration-${k}`, `${v}ms`);
	for (const [k, v] of Object.entries(tokens.motion.easing)) add(`motion-easing-${k}`, v);
	for (const [k, v] of Object.entries(tokens.z)) add(`z-${k}`, v);
	for (const [k, v] of Object.entries(tokens.layout)) add(`layout-${kebab(k)}`, px(v));
	return out;
}

/** Semantic colours + shadows for one theme (Appendix F §2.5), plus the `--sl-color-accent` alias. */
function themeDecls(theme: Theme): Decl[] {
	const out: Decl[] = [];
	for (const [key, ref] of Object.entries(tokens.color[theme]))
		out.push([`${PREFIX}color-${kebab(key)}`, resolveColor(ref)]);
	out.push([`${PREFIX}color-accent`, resolveColor({ ref: "brand.500" })]);
	for (const [key, layers] of Object.entries(tokens.shadow[theme]))
		out.push([`${PREFIX}shadow-${key}`, shadow(layers)]);
	return out;
}

function highContrastDecls(theme: Theme): Decl[] {
	return Object.entries(tokens.color.highContrast[theme]).map(
		([key, ref]) => [`${PREFIX}color-${kebab(key)}`, resolveColor(ref)] as const
	);
}

function typeRoleDecls(role: keyof typeof tokens.type.roles): Decl[] {
	const r = tokens.type.roles[role];
	const out: Decl[] = [
		["font-family", `var(${PREFIX}type-family-${r.family})`],
		["font-size", `var(${PREFIX}type-size-${r.size})`],
		["line-height", `var(${PREFIX}type-leading-${r.size})`],
		["font-weight", `var(${PREFIX}type-weight-${r.weight})`],
		["letter-spacing", `var(${PREFIX}type-tracking-${r.tracking})`],
	];
	if (r.family === "display")
		out.push(["font-feature-settings", `var(${PREFIX}type-features-numerals)`]);
	if (r.family === "mono") out.push(["font-feature-settings", `var(${PREFIX}type-features-mono)`]);
	return out;
}

function rule(selector: string, decls: readonly Decl[], indent = ""): string {
	const body = decls.map(([n, v]) => `${indent}\t${n}: ${v};`).join("\n");
	return `${indent}${selector} {\n${body}\n${indent}}\n`;
}

export function renderCss(): string {
	const parts: string[] = [
		"/* GENERATED by scripts/gen-tokens.ts from src/design/tokens.ts — do not edit. */\n",
		rule(":root", [...structuralDecls(), ...themeDecls("dark")]),
		rule('[data-theme="dark"]', themeDecls("dark")),
		rule('[data-theme="light"]', themeDecls("light")),
	];
	const hcDark = highContrastDecls("dark");
	const hcLight = highContrastDecls("light");
	if (hcDark.length || hcLight.length) {
		let media = "@media (prefers-contrast: more) {\n";
		if (hcDark.length) media += rule(':root, [data-theme="dark"]', hcDark, "\t");
		if (hcLight.length) media += rule('[data-theme="light"]', hcLight, "\t");
		parts.push(`${media}}\n`);
	}
	for (const role of Object.keys(tokens.type.roles) as Array<keyof typeof tokens.type.roles>)
		parts.push(rule(`.sl-type-${role}`, typeRoleDecls(role)));
	return parts.join("\n");
}
