// scripts/gen-tokens/ts.ts — `src/design/tokens.generated.ts`: `TOKENS` for JS consumers
// (animation manager, highlight colours), byte-identical in value to `css/tokens.css`.

import { tokens } from "../../src/design/tokens";
import {
	camel,
	durationsMs,
	resolveColor,
	shadow,
	type Theme,
	typeSize,
	typeSteps,
} from "./resolve";

type Json = string | number | boolean | null | readonly Json[] | { readonly [k: string]: Json };

/** Deterministic TS literal: quotes keys only when needed, tabs, trailing commas. */
function literal(v: Json, depth: number): string {
	if (v === null || typeof v !== "object") return JSON.stringify(v);
	const pad = "\t".repeat(depth + 1);
	const close = "\t".repeat(depth);
	if (Array.isArray(v)) {
		if (v.length === 0) return "[]";
		return `[\n${v.map((x) => `${pad}${literal(x, depth + 1)},`).join("\n")}\n${close}]`;
	}
	const entries = Object.entries(v as { readonly [k: string]: Json });
	if (entries.length === 0) return "{}";
	const body = entries
		.map(([k, x]) => {
			const key = /^(?:[A-Za-z_$][\w$]*|\d+)$/.test(k) ? k : JSON.stringify(k);
			return `${pad}${key}: ${literal(x, depth + 1)},`;
		})
		.join("\n");
	return `{\n${body}\n${close}}`;
}

function themeColors(theme: Theme): Record<string, string> {
	const out: Record<string, string> = {};
	for (const [key, ref] of Object.entries(tokens.color[theme])) out[camel(key)] = resolveColor(ref);
	out.accent = resolveColor({ ref: "brand.500" });
	return out;
}

function themeShadows(theme: Theme): Record<string, string> {
	const out: Record<string, string> = {};
	for (const [key, layers] of Object.entries(tokens.shadow[theme])) out[key] = shadow(layers);
	return out;
}

function pxMap(m: Record<string, number>): Record<string, number> {
	const out: Record<string, number> = {};
	for (const [k, n] of Object.entries(m)) out[k] = n * tokens.unit;
	return out;
}

/** Radius in px: unit multiples resolved, `full` parsed from its px literal. */
function radiusPx(): Record<string, number> {
	const out: Record<string, number> = {};
	for (const [k, v] of Object.entries(tokens.radius))
		out[k] = typeof v === "number" ? v * tokens.unit : Number.parseInt(v, 10);
	return out;
}

export function renderTs(): string {
	const size: Record<string, number> = {};
	const leading: Record<string, number> = {};
	for (const step of typeSteps()) {
		size[step] = typeSize(step);
		leading[step] = tokens.type.leading[step];
	}
	const iconSize: Record<string, number> = {};
	for (const [k, ref] of Object.entries(tokens.size.icon)) {
		const resolved = size[ref.slice("type.".length)];
		if (resolved === undefined) throw new Error(`size.icon.${k} references unknown step "${ref}"`);
		iconSize[k] = resolved;
	}
	const data: Json = {
		unit: tokens.unit,
		space: pxMap(tokens.space),
		size: {
			control: pxMap(tokens.size.control),
			icon: iconSize,
			touch: tokens.size.touch * tokens.unit,
			rail: tokens.size.rail * tokens.unit,
			hairline: 1,
			column: tokens.size.column,
			logPane: tokens.size.logPane * tokens.unit,
		},
		radius: radiusPx(),
		color: { dark: themeColors("dark"), light: themeColors("light") },
		shadow: { dark: themeShadows("dark"), light: themeShadows("light") },
		motion: { durationMs: durationsMs(), easing: tokens.motion.easing },
		layout: tokens.layout,
		type: {
			family: tokens.type.family,
			size,
			leading,
			weight: tokens.type.weight,
			tracking: tokens.type.tracking,
			features: tokens.type.features,
		},
		z: tokens.z,
	};
	return [
		"// GENERATED by scripts/gen-tokens.ts from src/design/tokens.ts — do not edit.",
		"// Resolved Lattice tokens for JS consumers; values are byte-identical to css/tokens.css.",
		`export const TOKENS = ${literal(data, 0)} as const;`,
		"",
		"export type Tokens = typeof TOKENS;",
		'export type ThemeName = keyof Tokens["color"];',
		"",
	].join("\n");
}
