#!/usr/bin/env python3
"""Human reference for the clock left after move 40 at 10+0, from the chess.com crawl.

    tools/data/.venv/bin/python tools/timing-finetune/human_clock_reference.py \
        [--games data/timing/crawl/games.jsonl] [--out test/fixtures/human-clock-reference.json]

Population: rapid games with time control "600" (10+0), movers rated 2300–2499, sides the crawl
kept (`whiteKept`/`blackKept`: its per-player caps, ≤ 30 game-sides per player per time class),
sides that played a 40th move with a readable [%clk]. The statistic is that side's clock after
its 40th move, in seconds. Reported: median, p25, p75, and a 95 % percentile bootstrap envelope of
the median that resamples players (their sides are correlated). `test/core/timing/
blitz-clock-budget.test.ts` requires the bot's median at move 40 to lie in [p25, p75].
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import cmenc  # noqa: E402
import extract  # noqa: E402

CONTROL = "600"
RATING = (2300, 2500)  # [lo, hi)
MOVE = 40


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", default=str(cmenc.ROOT / "data" / "timing" / "crawl" / "games.jsonl"))
    ap.add_argument("--out", default=str(cmenc.ROOT / "test" / "fixtures" / "human-clock-reference.json"))
    ap.add_argument("--boot", type=int, default=2000)
    args = ap.parse_args()
    values: list[float] = []
    players: list[str] = []
    games: set[str] = set()
    read = 0
    with open(args.games, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if not line.endswith("\n"):
                break
            read += 1
            if f'"time_control":"{CONTROL}"' not in line:
                continue
            parsed = extract.parse_game(line)
            if parsed is None:
                continue
            g, tc, base, inc, sans, clocks = parsed
            if g.get("time_class") != "rapid" or base != 600 or inc != 0:
                continue
            for side, colour in ((0, "white"), (1, "black")):
                info = g[colour]
                rating = float(info.get("rating") or 0)
                if not (RATING[0] <= rating < RATING[1]) or not g.get(f"{colour}Kept", True):
                    continue
                ply = 2 * (MOVE - 1) + side
                if ply >= len(clocks) or clocks[ply] is None:
                    continue
                values.append(float(clocks[ply]))
                players.append(info["username"].lower())
                games.add(g["uuid"])
    v = np.asarray(values)
    uniq, inv = np.unique(players, return_inverse=True)
    rng = np.random.default_rng(40)
    by_player = [v[inv == i] for i in range(len(uniq))]
    boots = np.empty(args.boot)
    for b in range(args.boot):
        pick = rng.integers(0, len(uniq), len(uniq))
        boots[b] = np.median(np.concatenate([by_player[i] for i in pick]))
    ref = {
        "note": "Clock left (s) after the side's 40th move, chess.com 10+0 rapid, movers rated 2300-2499, crawl-kept sides. Generated by tools/timing-finetune/human_clock_reference.py; used by test/core/timing/blitz-clock-budget.test.ts (see docs/models.md section 9).",
        "source": "data/timing/crawl/games.jsonl (public chess.com games)",
        "generated": dt.date.today().isoformat(),
        "filters": {"timeControl": CONTROL, "timeClass": "rapid", "ratingMin": RATING[0], "ratingMaxExclusive": RATING[1], "keptSidesOnly": True, "move": MOVE},
        "gamesRead": read,
        "sides": int(len(v)),
        "games": len(games),
        "players": int(len(uniq)),
        "medianS": round(float(np.median(v)), 1),
        "p25S": round(float(np.percentile(v, 25)), 1),
        "p75S": round(float(np.percentile(v, 75)), 1),
        "medianCi95S": [round(float(np.percentile(boots, 2.5)), 1), round(float(np.percentile(boots, 97.5)), 1)],
        "shareAtLeast240S": round(float((v >= 240).mean()), 3),
    }
    Path(args.out).write_text(json.dumps(ref, indent="\t") + "\n", encoding="utf-8")
    print(json.dumps(ref, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
