// scripts/gen-pagescript.ts — build step `gen-pagescript` (§5.4, Task 6).
//
// Compiles every program in the registry (`src/page/index.ts`) with the build
// spoof seed and writes:
//   src/page/generated/<name>.ts   — `{ name, params, code, bind(args) }`, runtime-safe
//                                    (no imports; `bind` mirrors src/pagescript/bind.ts)
//   <dist>/js/page/<name>.js       — for `entry` programs: the bound code as an IIFE
//                                    (MAIN-world content script registered in the manifest)
//
// `astring` and the builders never reach a shipped bundle: runtime code imports
// only the generated modules. With an empty registry the directories are still
// created and the step succeeds.
//
// Seed: `--seed <value>` / `SL_SPOOF_SEED` env (the build passes its
// `__SL_SPOOF_SEED__`), else the fixed dev seed.

import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
	type AnyPageProgram,
	bindCode,
	DEV_SPOOF_SEED,
	emit,
	type ParamSpec,
	type ParamType,
	paramPlaceholder,
} from "../src/pagescript";

export const ROOT = path.resolve(import.meta.dir, "..");
export const GENERATED_DIR = path.join(ROOT, "src", "page", "generated");
export const SEED_ENV = "SL_SPOOF_SEED";

export interface GenerateOptions {
	/** Spoof seed; defaults to `SL_SPOOF_SEED` from the environment, then the dev seed. */
	seed?: string;
	/** Where the `.ts` modules go (default `src/page/generated`). */
	generatedDir?: string;
	/** Program registry (default: `src/page/index.ts`). */
	programs?: readonly AnyPageProgram[];
}

export interface GenerateResult {
	seed: string;
	generated: string[];
	entries: string[];
}

const TS_TYPE: Record<ParamType, string> = {
	string: "string",
	number: "number",
	boolean: "boolean",
	json: "Json",
};

const FILE_NAME_RE = /^[A-Za-z][\w-]*$/;

/** Source of `src/page/generated/<name>.ts`. Self-contained: no imports. */
export function renderModule(name: string, params: readonly ParamSpec[], code: string): string {
	const args = params.map((p) => `\t${p.name}: ${TS_TYPE[p.type]};`).join("\n");
	const argsType = params.length === 0 ? "Record<string, never>" : `{\n${args}\n}`;
	return [
		`// Generated by scripts/gen-pagescript.ts from page program "${name}". Do not edit.`,
		"// Runtime-safe: no imports. `bind` mirrors src/pagescript/bind.ts.",
		"",
		"type Json = string | number | boolean | null | readonly Json[] | { readonly [key: string]: Json };",
		"",
		`export const name = ${JSON.stringify(name)};`,
		`export const params = ${JSON.stringify(params)} as const;`,
		`export const code = ${JSON.stringify(code)};`,
		`export type Args = ${argsType};`,
		"",
		"function encode(param: string, type: string, value: unknown): string {",
		"\tswitch (type) {",
		'\t\tcase "string":',
		'\t\t\tif (typeof value === "string") return JSON.stringify(value);',
		"\t\t\tbreak;",
		'\t\tcase "number":',
		'\t\t\tif (typeof value === "number" && Number.isFinite(value)) return String(value);',
		"\t\t\tbreak;",
		'\t\tcase "boolean":',
		'\t\t\tif (typeof value === "boolean") return String(value);',
		"\t\t\tbreak;",
		"\t\tdefault: {",
		"\t\t\tconst encoded = value === undefined ? undefined : JSON.stringify(value);",
		'\t\t\tif (typeof encoded === "string") return encoded;',
		"\t\t}",
		"\t}",
		'\tthrow new TypeError("bind(" + JSON.stringify(param) + "): expected " + type + ", got " + typeof value);',
		"}",
		"",
		"export function bind(args: Args): string {",
		"\tconst values: Record<string, unknown> = args;",
		"\tlet out = code;",
		"\tfor (const p of params) {",
		'\t\tif (!(p.name in values)) throw new TypeError("bind: missing argument " + JSON.stringify(p.name));',
		"\t\tconst encoded = encode(p.name, p.type, values[p.name]);",
		`\t\tout = out.replaceAll(${JSON.stringify(paramPlaceholder("").slice(0, -1))} + p.name + '"', () => encoded);`,
		"\t}",
		"\treturn out;",
		"}",
		"",
	].join("\n");
}

/** Source of `<dist>/js/page/<name>.js`: the bound program wrapped as an IIFE. */
export function renderEntry(boundCode: string): string {
	return `(() => {\n${boundCode}\n})();\n`;
}

function parseSeedArg(argv: readonly string[]): string | undefined {
	const i = argv.indexOf("--seed");
	return i >= 0 ? argv[i + 1] : undefined;
}

/** Compile the registry (or `options.programs`) and write the generated files. */
export async function generatePrograms(
	dist: string,
	options: GenerateOptions = {}
): Promise<GenerateResult> {
	const seed = options.seed ?? process.env[SEED_ENV] ?? DEV_SPOOF_SEED;
	const generatedDir = options.generatedDir ?? GENERATED_DIR;
	const entryDir = path.join(dist, "js", "page");
	const programs = options.programs ?? (await import("../src/page/index.ts")).programs;

	await rm(generatedDir, { recursive: true, force: true });
	await mkdir(generatedDir, { recursive: true });
	await mkdir(entryDir, { recursive: true });

	const seen = new Set<string>();
	const generated: string[] = [];
	const entries: string[] = [];
	for (const program of programs) {
		if (!FILE_NAME_RE.test(program.name)) {
			throw new Error(`gen-pagescript: program name "${program.name}" is not a safe file name`);
		}
		if (seen.has(program.name)) {
			throw new Error(`gen-pagescript: duplicate program name "${program.name}"`);
		}
		seen.add(program.name);

		const { code, params } = emit(program, { seed });
		const modulePath = path.join(generatedDir, `${program.name}.ts`);
		await writeFile(modulePath, renderModule(program.name, params, code));
		generated.push(modulePath);

		if (!program.entry) continue;
		if (params.length > 0 && program.entryArgs === undefined) {
			throw new Error(
				`gen-pagescript: entry program "${program.name}" declares parameters but no entryArgs`
			);
		}
		const bound = bindCode(code, params, program.entryArgs ?? {});
		const entryPath = path.join(entryDir, `${program.name}.js`);
		await writeFile(entryPath, renderEntry(bound));
		entries.push(entryPath);
	}
	return { seed, generated, entries };
}

/** Build step entry (`scripts/build.ts` → `gen-pagescript`). */
export async function generatePagescript(
	dist: string,
	options: GenerateOptions = {}
): Promise<void> {
	await generatePrograms(dist, options);
}

if (import.meta.main) {
	const argv = process.argv.slice(2);
	const seed = parseSeedArg(argv);
	const result = await generatePrograms(path.join(ROOT, "dist"), seed === undefined ? {} : { seed });
	console.log(
		`gen-pagescript: ${result.generated.length} program(s), ${result.entries.length} entry file(s)`
	);
}
