// scripts/vendor-engine/notice/books.ts — the opening-books section, rendered from the
// `<book>.build.json` manifests the Python builders write (Task 15; theory book 2026-09-15).

import type { VendoredFile } from "../../lib/fs";
import type { BookManifest, TheoryBookManifest } from "../manifests";
import { count, fileRow } from "./table";

const LICHESS_DB = "https://database.lichess.org/";
const LICHESS_ELITE_DB = "https://database.nikonoel.fr/";

export interface BooksNotice {
	dir: string;
	/** The Polyglot game books in `BOOKS.dir` (Task 15), each with its build manifest. */
	books: Array<{ file: VendoredFile; manifest: BookManifest }>;
	/** The named-opening theory book (2026-09-15); omitted → no theory row. */
	theoryBook?: { file: VendoredFile; manifest: TheoryBookManifest };
}

/** The literal `build-club-book.py` invocation recorded by a manifest. */
export function bookCommand(dir: string, m: BookManifest): string {
	const f = m.filters;
	const flags = [
		`--min-elo ${f.min_elo}`,
		...(f.max_elo === null ? [] : [`--max-elo ${f.max_elo}`]),
		...(f.max_ply === 30 ? [] : [`--max-ply ${f.max_ply}`]),
		`--min-count ${f.min_count_requested}`,
		...(f.min_position ? [`--min-position ${f.min_position}`] : []),
		...(f.min_share ? [`--min-share ${f.min_share}`] : []),
		`--max-bytes ${f.max_bytes}`,
		...(f.max_games ? [`--max-games ${f.max_games}`] : []),
		...(f.keep_bullet ? ["--keep-bullet"] : []),
		...(f.allow_unrated ? ["--allow-unrated"] : []),
		`--output ${dir}${m.book}`,
	];
	const inputs = m.inputs.map((i) => `--input ${i}`).join(" ");
	const numpy = m.input_sha256 ? " --with numpy" : "";
	return `uv run --with chess --with zstandard${numpy} ${m.script} ${inputs} ${flags.join(" ")}`;
}

/** The literal `build-theory-book.py` invocation recorded by a theory manifest. */
export function theoryBookCommand(dir: string, m: TheoryBookManifest): string {
	const inputs = m.inputs.map((i) => `--input ${i}`).join(" ");
	return `uv run --with chess ${m.script} ${inputs} --output ${dir}${m.book}`;
}

function describeFilter(m: BookManifest): string {
	const f = m.filters;
	const elo = f.max_elo === null ? `≥ ${f.min_elo}` : `${f.min_elo}–${f.max_elo}`;
	const unrated = f.allow_unrated ? " (or unrated)" : "";
	const bullet = f.keep_bullet ? "" : ", no bullet";
	const position = f.min_position ? `, position reached ≥ ${f.min_position} times` : "";
	const share = f.min_share ? `, ≥ ${f.min_share * 100} % of the position's games` : "";
	return `both players rated ${elo}${unrated}${bullet}, first ${f.max_ply} plies, ≥ ${f.min_count} games per move${position}${share}`;
}

function renderTheoryParagraph(dir: string, theory: TheoryBookManifest): string {
	return `
\`${theory.book}\` is generated by \`${theory.script}\` from the Lichess
\`chess-openings\` dataset (${theory.source}, CC0 1.0): every move of every named opening
line, for both sides, weighted by the number of named lines through it —
${count(theory.lines)} lines, ${count(theory.entries)} entries.
Inputs are the unmodified \`a.tsv\`…\`e.tsv\` (SHA-256 in its manifest):

    ${theoryBookCommand(dir, theory)}
`;
}

/** From the section heading through the file table (no trailing newline). */
export function renderBooksSection(n: BooksNotice): string {
	return `## Opening books — \`${n.dir}\`

The game books are generated by \`scripts/build-club-book.py\` from games in the Lichess open
database (${LICHESS_DB} — rated games, and OTB broadcasts as \`lichess_db_broadcast_*\`), which
Lichess releases under the Creative Commons CC0 1.0 public-domain dedication; \`lichess_elite_*.zip\`
inputs are the Lichess Elite Database (${LICHESS_ELITE_DB}), a subset of that database (2400+ vs
2200+ until November 2021, 2500+ vs 2300+ after; no bullet). A \`.first6GiB\`-style input name is
the first bytes of the named monthly file, read up to its last complete game. Nothing under
\`${n.dir}\` is copied from a third-party book file. Each book ships with a
\`<book>.build.json\` manifest; the rows below are rendered from those manifests.

| File | Inputs | Filter | Games kept / read | Entries |
|---|---|---|---|---|
${n.books
	.map(
		({ manifest: m }) =>
			`| \`${m.book}\` | ${m.inputs.map((i) => `\`${i}\``).join(", ")} | ${describeFilter(m)} | ${count(m.games_kept)} / ${count(m.games_read)} | ${count(m.entries)} |`
	)
	.join("\n")}

Exact invocations (inputs are the unmodified downloads):

${n.books.map(({ manifest: m }) => `    ${bookCommand(n.dir, m)}`).join("\n\n")}
${n.theoryBook ? renderTheoryParagraph(n.dir, n.theoryBook.manifest) : ""}
The Polyglot \`Random64\` table in \`src/core/strength/book/random64.ts\` is transcribed from
Michel Van den Bergh's format description (http://hgm.nubati.net/book_format.html), which states
the table is not subject to copyright and releases its sample code into the public domain.

Note: the \`gm2600\` registry key follows the plan's naming; the file is **not** the SCID/Pascal
Georges \`gm2600.bin\`, whose licence forbids reuse without the author's permission.

| File | Bytes | SHA-256 |
|---|---|---|
${[...n.books.map(({ file }) => fileRow(file)), ...(n.theoryBook ? [fileRow(n.theoryBook.file)] : [])].join("\n")}`;
}
