// scripts/vendor-engine/notice/third-party.ts — `docs/third-party.md`, assembled from its
// sections. Pure: every input is a verified description, so the same assets always render the
// same bytes (never hand-edit the output; re-run `bun run vendor:engine`).

import type { VendoredFile } from "../../lib/fs";
import type { VendoredFont } from "../fonts";
import type { BookManifest, MaiaNotice, ModelsNotice, TheoryBookManifest } from "../manifests";
import { renderBooksSection } from "./books";
import { renderFontsSection } from "./fonts";
import { renderMaiaSection } from "./maia";
import { renderModelsSection } from "./models";
import { renderOnnxRuntimeSection } from "./onnxruntime";
import { renderStockfishSection, type StockfishNotice } from "./stockfish";

export interface ThirdPartyNotice extends StockfishNotice {
	/** The Polyglot game books in `BOOKS.dir` (Task 15), each with its build manifest. */
	books: Array<{ file: VendoredFile; manifest: BookManifest }>;
	/** The named-opening theory book (2026-09-15); omitted → no theory row. */
	theoryBook?: { file: VendoredFile; manifest: TheoryBookManifest };
	/** Task 27: the vendored UI fonts (`describeFonts()`); omitted → no fonts section. */
	fonts?: VendoredFont[];
	/** Task 34: the exported ChessMimic bands (`describeModels()`); omitted → no models section. */
	models?: ModelsNotice;
	/** Task 34: the vendored onnxruntime-web files (`vendorOnnxRuntime()`); omitted → no section. */
	onnxruntime?: VendoredFile[];
	/** Maia-3: the exported policy models (`describeMaia()`); omitted → no section. */
	maia?: MaiaNotice;
}

/** An optional section framed by blank lines, or nothing. */
const optional = (text: string | undefined): string => (text === undefined ? "" : `\n${text}\n`);

export function renderThirdParty(n: ThirdPartyNotice): string {
	const { registry } = n;
	const models = n.models ? renderModelsSection(registry, n.models) : undefined;
	const maia = n.maia ? renderMaiaSection(registry.maia, n.maia, registry.website) : undefined;
	const ort = n.onnxruntime ? renderOnnxRuntimeSection(registry, n.onnxruntime) : undefined;
	const books = renderBooksSection({
		dir: registry.BOOKS.dir,
		books: n.books,
		...(n.theoryBook ? { theoryBook: n.theoryBook } : {}),
	});
	return `# Third-party components

<!-- Generated by \`bun run vendor:engine\` (scripts/vendor-engine.ts); do not edit by hand. -->

${renderStockfishSection(n)}
${optional(models)}${optional(maia)}${optional(ort)}
${books}
${n.fonts ? `\n${renderFontsSection(n.fonts)}` : ""}`;
}
