// test/scripts/chessmimic-assets.test.ts — Task 34: the shipped model/runtime assets match the
// registry (`src/core/constants/models.ts`), the export manifest and the pinned npm package.
import { describe, expect, it } from "bun:test";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import {
	CHESSMIMIC_BAND_FILES,
	CHESSMIMIC_BANDS,
	CHESSMIMIC_DEFAULT_BAND,
	CHESSMIMIC_FILES,
	CHESSMIMIC_UPSTREAM,
	chessMimicBandFile,
	MODELS_DIR,
	ORT_DIR,
	ORT_FILES,
	ORT_PACKAGE,
	ORT_VERSION,
} from "@core/constants/models";
import { TIMING_CONSTANTS } from "@core/timing/constants";
import pkg from "../../package.json";

const ROOT = path.resolve(import.meta.dir, "../..");

interface Manifest {
	upstream: { repo: string; commit: string; license: string };
	export: { opset: number; precision: string };
	bands: Record<
		string,
		{ file: string; bytes: number; sha256: string; maxAbsProbDiffOnnxVsTorch: number }
	>;
}

function sha256(file: string): string {
	return createHash("sha256").update(readFileSync(file)).digest("hex");
}

describe("ChessMimic assets", () => {
	const manifest = JSON.parse(
		readFileSync(path.join(ROOT, MODELS_DIR, CHESSMIMIC_FILES.manifest), "utf8")
	) as Manifest;
	it("models.json records the pinned upstream commit and licence", () => {
		expect(manifest.upstream).toEqual({
			repo: CHESSMIMIC_UPSTREAM.repo,
			commit: CHESSMIMIC_UPSTREAM.commit,
			license: CHESSMIMIC_UPSTREAM.license,
		});
		expect(manifest.export.opset).toBe(14);
		expect(manifest.export.precision).toBe("fp16");
	});
	it("every registered band's bytes and SHA-256 match the manifest and the file on disk", () => {
		expect(Object.keys(manifest.bands).sort()).toEqual([...CHESSMIMIC_BANDS].sort());
		for (const band of CHESSMIMIC_BANDS) {
			const reg = CHESSMIMIC_BAND_FILES[band];
			const man = manifest.bands[band];
			if (!man) throw new Error(`manifest lacks ${band}`);
			expect(man.file).toBe(chessMimicBandFile(band));
			expect(reg.bytes).toBe(man.bytes);
			expect(reg.sha256).toBe(man.sha256);
			const file = path.join(ROOT, MODELS_DIR, man.file);
			expect(statSync(file).size).toBe(reg.bytes);
			expect(sha256(file)).toBe(reg.sha256);
			// The export's own onnxruntime check stays inside the registered tolerance.
			expect(man.maxAbsProbDiffOnnxVsTorch).toBeLessThan(
				TIMING_CONSTANTS.chessmimic.fixtureProbTolerance
			);
		}
	});
	it("the pre-warmed default band is registered and bundled, so warming needs no download", () => {
		expect([...CHESSMIMIC_BANDS]).toContain(CHESSMIMIC_DEFAULT_BAND);
		expect(CHESSMIMIC_BAND_FILES[CHESSMIMIC_DEFAULT_BAND].bundled).toBe(true);
	});
	it("the side files and the reference fixture exist", () => {
		for (const f of [CHESSMIMIC_FILES.scalers, CHESSMIMIC_FILES.buckets, CHESSMIMIC_FILES.vocab])
			expect(existsSync(path.join(ROOT, MODELS_DIR, f))).toBe(true);
		expect(existsSync(path.join(ROOT, "test/fixtures/chessmimic-reference.json"))).toBe(true);
	});
});

describe("onnxruntime-web vendoring", () => {
	it("is pinned exactly in package.json and the installed package has that version", () => {
		const dev = (pkg as { devDependencies: Record<string, string> }).devDependencies;
		expect(dev[ORT_PACKAGE]).toBe(ORT_VERSION);
		const installed = JSON.parse(
			readFileSync(path.join(ROOT, "node_modules", ORT_PACKAGE, "package.json"), "utf8")
		) as { version: string; license: string };
		expect(installed.version).toBe(ORT_VERSION);
		expect(installed.license).toBe("MIT");
	});
	it("the vendored runtime files are byte-identical to the package's dist files", () => {
		for (const name of [ORT_FILES.module, ORT_FILES.loader, ORT_FILES.wasm]) {
			const vendored = path.join(ROOT, ORT_DIR, name);
			const upstream = path.join(ROOT, "node_modules", ORT_PACKAGE, "dist", name);
			expect(existsSync(vendored)).toBe(true);
			expect(sha256(vendored)).toBe(sha256(upstream));
		}
		const license = readFileSync(path.join(ROOT, ORT_DIR, ORT_FILES.license), "utf8");
		expect(license).toContain("MIT License");
		expect(license).toContain("Microsoft Corporation");
	});
	it("docs/third-party.md carries both notices (generated by scripts/vendor-engine.ts)", () => {
		const doc = readFileSync(path.join(ROOT, "docs/third-party.md"), "utf8");
		expect(doc).toContain(CHESSMIMIC_UPSTREAM.licenseName);
		expect(doc).toContain(CHESSMIMIC_UPSTREAM.commit);
		expect(doc).toContain(`${ORT_PACKAGE}\` ${ORT_VERSION}`);
		for (const band of CHESSMIMIC_BANDS) expect(doc).toContain(CHESSMIMIC_BAND_FILES[band].sha256);
	});
});
