// test/scripts/vendor-engine.test.ts — NNUE hash-prefix verification + vendored asset presence
// (Task 10, §6.2 / Appendix A §5).

import { describe, expect, it } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import {
	BOOKS,
	ENGINE_DIR,
	ENGINE_FILES,
	ENGINE_LICENSE_FILE,
	ENGINE_NNUE_SOURCES,
	ENGINE_PROGRAM_FILES,
	LIMITS,
	PACKAGED_ENGINE_FILES,
} from "@core/constants";
import {
	MAIA_DIR,
	MAIA_FILES,
	MAIA_MODEL_FILES,
	MAIA_SIZES,
	MAIA_UPSTREAM,
} from "@core/constants/maia";
import { readNnueSource } from "../../scripts/nnue-assets";
import {
	nnueHashPrefix,
	packageFiles,
	ROOT,
	readBookManifests,
	sha256Hex,
	staleEngineFiles,
	type TheoryBookManifest,
	theoryBookCommand,
	verifyNnueHash,
} from "../../scripts/vendor-engine";

const engineDir = path.join(ROOT, ENGINE_DIR);
const netName = ENGINE_FILES.smallnet.nnue;
const net = new Uint8Array(readFileSync(path.join(engineDir, netName)));

describe("verifyNnueHash", () => {
	it("accepts the real bundled net", () => {
		expect(sha256Hex(net).startsWith(nnueHashPrefix(netName) ?? "?")).toBe(true);
		expect(verifyNnueHash(net, netName)).toBe(true);
	});

	it("rejects a tampered buffer", () => {
		const tampered = new Uint8Array(net);
		const i = tampered.length >> 1;
		tampered[i] = (tampered[i] ?? 0) ^ 0xff;
		expect(verifyNnueHash(tampered, netName)).toBe(false);
		expect(verifyNnueHash(net.subarray(0, net.length - 1), netName)).toBe(false);
	});

	it("rejects a buffer that belongs to a different net name", () => {
		// The smallnet's bytes against every full-build net name (one since Stockfish 19).
		for (const name of LIMITS.nnueBigNames) expect(verifyNnueHash(net, name)).toBe(false);
	});

	it("rejects malformed net names instead of guessing", () => {
		// Derived from the registry rather than pinned: the hash changes with every vendored net, and
		// the name is already asserted to carry a 12-hex prefix by the ENGINE_FILES registry test.
		expect(nnueHashPrefix(netName)).toBe(netName.slice("nn-".length, -".nnue".length));
		// The malformed shapes: wrong case, one hex digit short, and no `nn-` prefix.
		expect(nnueHashPrefix("nn-4CA89E4B3ABF.nnue")).toBeUndefined();
		expect(nnueHashPrefix("nn-4ca89e4b3ab.nnue")).toBeUndefined();
		expect(nnueHashPrefix("4ca89e4b3abf.nnue")).toBeUndefined();
		expect(verifyNnueHash(net, "nn-.nnue")).toBe(false);
	});
});

describe("ENGINE_FILES registry", () => {
	it("every engine program and registered network source exists on disk", () => {
		for (const name of [...packageFiles(ENGINE_FILES), ...ENGINE_NNUE_SOURCES.map((s) => s.source)])
			expect(existsSync(path.join(engineDir, name))).toBe(true);
	});

	it("ships every verified network with only the compressed source checked in", async () => {
		for (const spec of ENGINE_NNUE_SOURCES) {
			const data = await readNnueSource(engineDir, spec);
			expect(verifyNnueHash(data, spec.name)).toBe(true);
		}
		// `ENGINE_NNUE_SOURCES` gzips exactly the first full net: that one is on disk only as `.gz`.
		expect(existsSync(path.join(engineDir, ENGINE_FILES.full.nnue[0]))).toBe(false);
		expect(existsSync(path.join(engineDir, `${ENGINE_FILES.full.nnue[0]}.gz`))).toBe(true);
		// Every other registered net is checked in raw (the smallnet's own since Stockfish 19).
		expect(existsSync(path.join(engineDir, ENGINE_FILES.smallnet.nnue))).toBe(true);
	});

	it("net names carry their hash prefix and are only defined in LIMITS", () => {
		expect(ENGINE_FILES.smallnet.nnue).toBe(LIMITS.nnueSmallName);
		expect(ENGINE_FILES.full.nnue).toBe(LIMITS.nnueBigNames);
		for (const name of [ENGINE_FILES.smallnet.nnue, ...ENGINE_FILES.full.nnue])
			expect(nnueHashPrefix(name)).toMatch(/^[0-9a-f]{12}$/);
	});

	it("the .js and .wasm of each variant are paired", () => {
		const { smallnet, full } = ENGINE_FILES;
		const pairs: ReadonlyArray<readonly [string, string]> = [
			[smallnet.js, smallnet.wasm],
			[full.js, full.wasm],
		];
		for (const [js, wasm] of pairs) expect(wasm).toBe(js.replace(/\.js$/, ".wasm"));
	});

	it("vendors only the relaxed-SIMD programs plus the licence, matching the packaged list", () => {
		expect(packageFiles(ENGINE_FILES)).toEqual([...ENGINE_PROGRAM_FILES, ENGINE_LICENSE_FILE]);
		for (const name of ENGINE_PROGRAM_FILES) expect(name).toContain("_relaxed-simd.");
		expect(PACKAGED_ENGINE_FILES).toEqual([
			...ENGINE_PROGRAM_FILES,
			ENGINE_LICENSE_FILE,
			LIMITS.nnueSmallName,
			...LIMITS.nnueBigNames,
		]);
	});

	it("names files in the engine directory the registry no longer ships", () => {
		const onDisk = [
			...packageFiles(ENGINE_FILES),
			...ENGINE_NNUE_SOURCES.map((s) => s.source),
			"sf_19.js",
			"sf_19.wasm",
			".DS_Store",
		];
		expect(staleEngineFiles(onDisk, ENGINE_FILES, ENGINE_NNUE_SOURCES)).toEqual([
			"sf_19.js",
			"sf_19.wasm",
		]);
	});
});

describe("docs/third-party.md Maia-3 section (generated by scripts/vendor-engine.ts)", () => {
	const doc = readFileSync(path.join(ROOT, "docs", "third-party.md"), "utf8");

	it("carries the AGPL notice, the source offer and every size's provenance", () => {
		expect(doc).toContain(`## Maia-3 human move-policy models — \`${MAIA_DIR}\``);
		expect(doc).toContain(MAIA_UPSTREAM.licenseName);
		expect(doc).toContain(`SPDX \`${MAIA_UPSTREAM.license}\``);
		expect(doc).toContain(MAIA_UPSTREAM.copyright);
		expect(doc).toContain(MAIA_UPSTREAM.paper);
		expect(doc).toContain(`${MAIA_DIR}${MAIA_FILES.license}`);
		// The Stockfish source offer is extended to cover Maia-3, and the Maia section points back.
		expect(doc).toContain("every other GPL/AGPL component in this document");
		expect(doc).toContain("The written offer in the Stockfish section");
		for (const size of MAIA_SIZES) {
			const reg = MAIA_MODEL_FILES[size];
			expect(doc).toContain(
				`| \`${reg.file}\` | ${reg.bytes.toLocaleString("en-US")} | \`${reg.sha256}\` |`
			);
			expect(doc).toContain(reg.upstream.repo);
			expect(doc).toContain(reg.upstream.revision.slice(0, 12));
			expect(doc).toContain(reg.upstream.sha256);
			for (let i = 0; i < reg.parts; i += 1)
				if (reg.parts > 1) expect(doc).toContain(`\`${reg.file}${MAIA_FILES.partSuffix}${i}\``);
		}
	});
});

describe("docs/third-party.md books section (Task 15)", () => {
	const doc = readFileSync(path.join(ROOT, "docs", "third-party.md"), "utf8");

	it("lists every bundled Polyglot book with its current SHA-256", () => {
		for (const name of [BOOKS.gm2600, BOOKS.club, BOOKS.theory]) {
			const file = path.join(ROOT, BOOKS.dir, name);
			expect(existsSync(file)).toBe(true);
			const sha = sha256Hex(new Uint8Array(readFileSync(file)));
			expect(doc).toContain(`| \`${name}\` |`);
			expect(doc).toContain(sha);
		}
		expect(doc).toContain("CC0");
		expect(doc).toContain("random64.ts");
	});

	it("each book's build manifest matches the file and the doc records its invocation", async () => {
		const books = await readBookManifests(path.join(ROOT, BOOKS.dir), [BOOKS.gm2600, BOOKS.club]);
		expect(books.map((b) => b.manifest.book)).toEqual([BOOKS.gm2600, BOOKS.club]);
		for (const { file, manifest } of books) {
			expect(manifest.sha256).toBe(file.sha256);
			expect(manifest.bytes).toBe(file.bytes);
			expect(manifest.entries * 16).toBe(file.bytes);
			expect(manifest.inputs.length).toBeGreaterThan(0);
			for (const input of manifest.inputs) expect(doc).toContain(`--input ${input}`);
			expect(doc).toContain(`--output ${BOOKS.dir}${manifest.book}`);
		}
	});

	it("the theory book's manifest matches the file and the doc records its source and invocation", async () => {
		const [theory] = await readBookManifests<TheoryBookManifest>(path.join(ROOT, BOOKS.dir), [
			BOOKS.theory,
		]);
		expect(theory?.manifest.kind).toBe("theory");
		expect(theory?.manifest.sha256).toBe(theory?.file.sha256 ?? "");
		expect((theory?.manifest.entries ?? 0) * 16).toBe(theory?.file.bytes ?? -1);
		expect(theory?.manifest.skipped_lines).toBe(0);
		expect(doc).toContain(theoryBookCommand(BOOKS.dir, theory?.manifest as TheoryBookManifest));
		expect(doc).toContain("chess-openings");
	});
});
