// scripts/gen-pagescript/module-template.ts — the text of the two generated artefacts: the
// runtime-safe `src/page/generated/<name>.ts` module and the `dist/js/page/<name>.js` IIFE.

import { type ParamSpec, type ParamType, placeholderPattern } from "../../src/pagescript";

const TS_TYPE: Record<ParamType, string> = {
	string: "string",
	number: "number",
	boolean: "boolean",
	json: "Json",
};

/** Source of `src/page/generated/<name>.ts`. Self-contained: no imports. */
export function renderModule(name: string, params: readonly ParamSpec[], code: string): string {
	const args = params.map((p) => `\t${p.name}: ${TS_TYPE[p.type]};`).join("\n");
	const argsType = params.length === 0 ? "Record<string, never>" : `{\n${args}\n}`;
	return [
		`// Generated by scripts/gen-pagescript.ts from page program "${name}". Do not edit.`,
		"// Runtime-safe: no imports. `bind` mirrors src/pagescript/bind.ts.",
		"",
		"type Json = string | number | boolean | null | readonly Json[] | { readonly [key: string]: Json };",
		'type ParamSpec = { name: string; type: "string" | "number" | "boolean" | "json" };',
		"",
		`export const name = ${JSON.stringify(name)};`,
		`export const params: readonly ParamSpec[] = ${JSON.stringify(params)};`,
		`export const code = ${JSON.stringify(code)};`,
		`export type Args = ${argsType};`,
		"",
		"function encode(param: string, type: string, value: unknown): string {",
		"\tswitch (type) {",
		'\t\tcase "string":',
		'\t\t\tif (typeof value === "string") return JSON.stringify(value);',
		"\t\t\tbreak;",
		'\t\tcase "number":',
		'\t\t\tif (typeof value === "number" && Number.isFinite(value)) return String(value);',
		"\t\t\tbreak;",
		'\t\tcase "boolean":',
		'\t\t\tif (typeof value === "boolean") return String(value);',
		"\t\t\tbreak;",
		"\t\tdefault: {",
		"\t\t\tconst encoded = value === undefined ? undefined : JSON.stringify(value);",
		'\t\t\tif (typeof encoded === "string") return encoded;',
		"\t\t}",
		"\t}",
		'\tthrow new TypeError("bind(" + JSON.stringify(param) + "): expected " + type + ", got " + typeof value);',
		"}",
		"",
		"export function bind(args: Args): string {",
		"\tconst values: Record<string, unknown> = args;",
		"\tconst encoded = new Map<string, string>();",
		"\tfor (const p of params) {",
		'\t\tif (!(p.name in values)) throw new TypeError("bind: missing argument " + JSON.stringify(p.name));',
		'\t\tencoded.set(p.name, "(" + encode(p.name, p.type, values[p.name]) + ")");',
		"\t}",
		`\treturn code.replace(${placeholderPattern().toString()}, (match, name: string) => {`,
		"\t\tconst value = encoded.get(name);",
		'\t\tif (value === undefined) throw new TypeError("bind: undeclared placeholder " + match);',
		"\t\treturn value;",
		"\t});",
		"}",
		"",
	].join("\n");
}

/** Source of `<dist>/js/page/<name>.js`: the bound program wrapped as an IIFE. */
export function renderEntry(boundCode: string): string {
	return `(() => {\n${boundCode}\n})();\n`;
}
